### ISSUE TITLE
Chapter 01 - 'Tap Me' crash on launch

### ISSUE THREAD

**Issue by eddie-long-pmd** [objcio/thinking-in-swiftui-sample-code#2]
I bought the book on paperback and cloned this repo to check out the sample code. Running the Tap Me app crashes on launch due to the `snapshot` function in SceneDelegate.swift. 

There is a reference to `florian`'s desktop which crashes.

https://github.com/objcio/thinking-in-swiftui-sample-code/blob/master/Chapter%2001/Tap%20Me/Tap%20Me/SceneDelegate.swift#L55

Temporary fix for now is to comment out the `snapshot()` call in SceneDelegate.swift.

**Comment by chriseidhof** [comment]
Ouch 😬

Should be fixed on master!
